### PR TITLE
Decode user and token returned by login flow.

### LINKED ISSUE #58: logon with email address as username not working
All users in my nextcloud have email address as username. Logon with talk-ios app failed with the following entries in nextcloud.log:

:“core”,“method”:“GET”,“url”:"/ocs/v2.php/apps/spreed/api/v1/room",“message”:“Login failed: ‘user%40email.de’ (Remote IP: ‘2003:aaaa:13e7:6800:f857:54f0:b764:aaaa’)”,“userAgent”:“Mozilla/5.0 (iOS) Nextcloud-Talk v1.1.0”,“version”:“13.0.0.14”}

I think the problem is that “@” in username is sendings as “%40”, i see the ‘user%40email.de’ also as auth-user in apache access.log instead of ‘user@email.de’.
Logon with the same user and use of talk-app with browser works without any problems.

### PR DESCRIPTION
**Pull request by Ivansss**
Fix #58

### CODE REVIEW

File: VideoCalls/AuthenticationViewController.m [hunk 1]
```diff
@@ -100,9 +100,9 @@ - (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigati
...
         {
             if ([component hasPrefix:userPrefix])
-                user = [component substringFromIndex:[userPrefix length]];
+                user = [[component substringFromIndex:[userPrefix length]] stringByRemovingPercentEncoding];
             if ([component hasPrefix:passPrefix])
-                token = [component substringFromIndex:[passPrefix length]];
+                token = [[component substringFromIndex:[passPrefix length]] stringByRemovingPercentEncoding];
         }
         
         NSLog(@"SERVER:%@ USER:%@ TOKEN:%@", _serverUrl, user, token);
```
Comment (mario) [inline VideoCalls/AuthenticationViewController.m:108]: Please remove logging :)

Comment (Ivansss) [reply VideoCalls/AuthenticationViewController.m:108]: Yeah, I think it's time to remove that log 😄
