### PR TITLE
Voice over accessibility labels 🗣

### LINKED ISSUE #293: Accessibility: Some missing button labels in Talk for iOS
## Steps to reproduce
1. Install NextCloud Talk from app store, currently v8.1.
2. Log into a server.
3. Start VoiceOver and explore the UI.

### Expected behaviour
All buttons should be labeled.

### Actual behaviour
Some buttons like the Settings button, the Audio and Video Call buttons in a conversation, are not labeled. VoiceOver may guess the label from the image name or its build-in text recognition on images, but that does not always work. Dedicated AccessibilityLabel properties on image buttons are better.

NextCloud for iOS on iPhone, version 8.1.0.

CC @nextcloud/accessibility

### PR DESCRIPTION
**Pull request by Ivansss**
Add missing accessibility labels to:
- Conversations list view
- Call view
- Chat view
- Conversation creation flow

Fix #293

### CODE REVIEW

File: VideoCalls/RoomsTableViewController.m [hunk 1]
```diff
@@ -265,6 +268,8 @@ - (void)setNavigationLogoButton
     } else {
         self.navigationItem.titleView = [[UIImageView alloc] initWithImage:logoImage];
     }
+    self.navigationItem.titleView.accessibilityLabel = @"Nextcloud Talk logo";
```
Comment (jancborchardt) [inline VideoCalls/RoomsTableViewController.m:271]: If it’s the Nextcloud Talk logo, it can just say "Nextcloud Talk". :)

Comment (Ivansss) [reply VideoCalls/RoomsTableViewController.m:271]: Changed in https://github.com/nextcloud/talk-ios/commit/d784065529fa04745967e98396e15fceede81e5a! :)
