### PR TITLE
Wait until all participants have been added before closing "Add Participants" view

### LINKED ISSUE #1635: Participants not visible after adding them in conversation settings
## Steps to reproduce
1. Go to conversation settings as a moderator in a group conversation
2. Add a participant

### Expected behaviour
When "Add participants" view is closed, the added participant should be visible in the participant list

### Actual behaviour
The added participant is not visible after the "Add participants" view is closed

### PR DESCRIPTION
**Pull request by Ivansss**
Fix #1635

### CODE REVIEW

File: NextcloudTalk/AddParticipantsTableViewController.m [hunk 1]
```diff
@@ -44,6 +44,8 @@ @interface AddParticipantsTableViewController () <UISearchBarDelegate, UISearchC
     PlaceholderView *_participantsBackgroundView;
     NSTimer *_searchTimer;
     NSURLSessionTask *_searchParticipantsTask;
+    UIActivityIndicatorView *_addingParticipantsIndicator;
+    BOOL _errorAddindParticipants;
```
Comment (SystemKeeper) [inline NextcloudTalk/AddParticipantsTableViewController.m]: I'd like to buy a `g` here

**Review by SystemKeeper — APPROVED** [review]
Tested and works
