### PR TITLE
fix(mentions): Highlight group and team mentions

### LINKED ISSUE #1996: Highlight Group and Team mentions

### PR DESCRIPTION
**Pull request by Ivansss**
Fix #1996

### CODE REVIEW

File: NextcloudTalk/NCAPIControllerExtensions.swift [hunk 1]
```diff
@@ -703,4 +703,43 @@ import Foundation
...
+    // MARK: - Groups & Teams
+
+    func getUserGroups(forAccount account: TalkAccount, completionBlock: @escaping (_ groupIds: [String]?, _ error: Error?) -> Void) {
+        guard let apiSessionManager = self.apiSessionManagers.object(forKey: account.accountId) as? NCAPISessionManager
+        else {
+            completionBlock(nil, NSError(domain: "", code: 0, userInfo: nil))
+            return
+        }
+
+        let urlString = "\(account.server)/ocs/v2.php/cloud/users/\(account.userId)/groups"
```
Comment (SystemKeeper) [inline NextcloudTalk/NCAPIControllerExtensions.swift]: I think we need to escape the userId:

https://github.com/nextcloud/talk-ios/blob/ba622764c1513e0e302a1f169b08d93c08c1eb13/NextcloudTalk/NCAPIControllerExtensions.swift#L527

File: NextcloudTalk/NCSettingsController.m [hunk 2]
```diff
@@ -416,6 +416,55 @@ - (void)getUserProfileForAccountId:(NSString *)accountId withCompletionBlock:(Up
...
+        if (!error) {
+            RLMRealm *realm = [RLMRealm defaultRealm];
+            [realm beginWriteTransaction];
+
+            NSPredicate *query = [NSPredicate predicateWithFormat:@"accountId = %@", account.accountId];
+            TalkAccount *managedActiveAccount = [TalkAccount objectsWithPredicate:query].firstObject;
+
+            if (!managedActiveAccount) {
+                return;
+            }
```
Comment (SystemKeeper) [inline NextcloudTalk/NCSettingsController.m]: I guess this will leave realm in a write transaction? Better use `transactionWithBlock` ? Same above.

**Review by SystemKeeper — APPROVED** [review]
